const data = {
  balance: {
    current: 5367,
    income: 3814.25,
    expenses: 1700.5,
  },
  transactions: [
    {
      avatar: './assets/images/avatars/emma-richardson.jpg',
      name: 'Emma Richardson',
      category: 'General',
      date: '2024-08-19T14:23:11Z',
      amount: 75.5,
      recurring: false,
      id: 'af82',
    },
    {
      avatar: './assets/images/avatars/savory-bites-bistro.jpg',
      name: 'Savory Bites Bistro',
      category: 'Dining Out',
      date: '2024-08-19T20:23:11Z',
      amount: -55.5,
      recurring: false,
      id: 'c439',
    },
    {
      avatar: './assets/images/avatars/daniel-carter.jpg',
      name: 'Daniel Carter',
      category: 'General',
      date: '2024-08-18T09:45:32Z',
      amount: -42.3,
      recurring: false,
      id: 'a23d',
    },
    {
      avatar: './assets/images/avatars/sun-park.jpg',
      name: 'Sun Park',
      category: 'General',
      date: '2024-08-17T16:12:05Z',
      amount: 120,
      recurring: false,
      id: '02d9',
    },
    {
      avatar: './assets/images/avatars/urban-services-hub.jpg',
      name: 'Urban Services Hub',
      category: 'General',
      date: '2024-08-17T21:08:09Z',
      amount: -65,
      recurring: false,
      id: '7280',
    },
    {
      avatar: './assets/images/avatars/liam-hughes.jpg',
      name: 'Liam Hughes',
      category: 'Groceries',
      date: '2024-08-15T18:20:33Z',
      amount: 65.75,
      recurring: false,
      id: '41fc',
    },
    {
      avatar: './assets/images/avatars/lily-ramirez.jpg',
      name: 'Lily Ramirez',
      category: 'General',
      date: '2024-08-14T13:05:27Z',
      amount: 50,
      recurring: false,
      id: '1b43',
    },
    {
      avatar: './assets/images/avatars/ethan-clark.jpg',
      name: 'Ethan Clark',
      category: 'Dining Out',
      date: '2024-08-13T20:15:59Z',
      amount: -32.5,
      recurring: false,
      id: 'fe31',
    },
    {
      avatar: './assets/images/avatars/james-thompson.jpg',
      name: 'James Thompson',
      category: 'Entertainment',
      date: '2024-08-11T15:45:38Z',
      amount: -5,
      recurring: false,
      id: 'e9b3',
    },
    {
      avatar: './assets/images/avatars/pixel-playground.jpg',
      name: 'Pixel Playground',
      category: 'Entertainment',
      date: '2024-08-11T18:45:38Z',
      amount: -10,
      recurring: true,
      id: 'a615',
    },
    {
      avatar: './assets/images/avatars/ella-phillips.jpg',
      name: 'Ella Phillips',
      category: 'Dining Out',
      date: '2024-08-10T19:22:51Z',
      amount: -45,
      recurring: false,
      id: '1c2b',
    },
    {
      avatar: './assets/images/avatars/sofia-peterson.jpg',
      name: 'Sofia Peterson',
      category: 'Transportation',
      date: '2024-08-08T08:55:17Z',
      amount: -15,
      recurring: false,
      id: '7c9a',
    },
    {
      avatar: './assets/images/avatars/mason-martinez.jpg',
      name: 'Mason Martinez',
      category: 'Lifestyle',
      date: '2024-08-07T17:40:29Z',
      amount: -35.25,
      recurring: false,
      id: '389e',
    },
    {
      avatar: './assets/images/avatars/green-plate-eatery.jpg',
      name: 'Green Plate Eatery',
      category: 'Groceries',
      date: '2024-08-06T08:25:44Z',
      amount: -78.5,
      recurring: false,
      id: 'd9ec',
    },
    {
      avatar: './assets/images/avatars/sebastian-cook.jpg',
      name: 'Sebastian Cook',
      category: 'Transportation',
      date: '2024-08-06T10:05:44Z',
      amount: -22.5,
      recurring: false,
      id: '39ab',
    },
    {
      avatar: './assets/images/avatars/william-harris.jpg',
      name: 'William Harris',
      category: 'Personal Care',
      date: '2024-08-05T14:30:56Z',
      amount: -10,
      recurring: false,
      id: 'fa13',
    },
    {
      avatar: './assets/images/avatars/elevate-education.jpg',
      name: 'Elevate Education',
      category: 'Education',
      date: '2024-08-04T11:15:22Z',
      amount: -50,
      recurring: true,
      id: 'dc8c',
    },
    {
      avatar: './assets/images/avatars/serenity-spa-and-wellness.jpg',
      name: 'Serenity Spa & Wellness',
      category: 'Personal Care',
      date: '2024-08-03T14:00:37Z',
      amount: -30,
      recurring: true,
      id: 'ee46',
    },
    {
      avatar: './assets/images/avatars/spark-electric-solutions.jpg',
      name: 'Spark Electric Solutions',
      category: 'Bills',
      date: '2024-08-02T09:25:11Z',
      amount: -100,
      recurring: true,
      id: 'd26c',
    },
    {
      avatar: './assets/images/avatars/rina-sato.jpg',
      name: 'Rina Sato',
      category: 'Bills',
      date: '2024-08-02T13:31:11Z',
      amount: -50,
      recurring: false,
      id: 'f80a',
    },
    {
      avatar: './assets/images/avatars/swift-ride-share.jpg',
      name: 'Swift Ride Share',
      category: 'Transportation',
      date: '2024-08-01T18:40:33Z',
      amount: -18.75,
      recurring: false,
      id: '3ce8',
    },
    {
      avatar: './assets/images/avatars/aqua-flow-utilities.jpg',
      name: 'Aqua Flow Utilities',
      category: 'Bills',
      date: '2024-07-30T13:20:14Z',
      amount: -100,
      recurring: true,
      id: 'd515',
    },
    {
      avatar: './assets/images/avatars/ecofuel-energy.jpg',
      name: 'EcoFuel Energy',
      category: 'Bills',
      date: '2024-07-29T11:55:29Z',
      amount: -35,
      recurring: true,
      id: '68e5',
    },
    {
      avatar: './assets/images/avatars/yuna-kim.jpg',
      name: 'Yuna Kim',
      category: 'Dining Out',
      date: '2024-07-29T13:51:29Z',
      amount: -28.5,
      recurring: false,
      id: 'f27c',
    },
    {
      avatar: './assets/images/avatars/flavor-fiesta.jpg',
      name: 'Flavor Fiesta',
      category: 'Dining Out',
      date: '2024-07-27T20:15:06Z',
      amount: -42.75,
      recurring: false,
      id: '48f1',
    },
    {
      avatar: './assets/images/avatars/harper-edwards.jpg',
      name: 'Harper Edwards',
      category: 'Shopping',
      date: '2024-07-26T09:43:23Z',
      amount: -89.99,
      recurring: false,
      id: '5c62',
    },
    {
      avatar: './assets/images/avatars/buzz-marketing-group.jpg',
      name: 'Buzz Marketing Group',
      category: 'General',
      date: '2024-07-26T14:40:23Z',
      amount: 3358,
      recurring: false,
      id: '6df1',
    },
    {
      avatar: './assets/images/avatars/technova-innovations.jpg',
      name: 'TechNova Innovations',
      category: 'Shopping',
      date: '2024-07-25T16:25:37Z',
      amount: -29.99,
      recurring: false,
      id: '0344',
    },
    {
      avatar: './assets/images/avatars/bytewise.jpg',
      name: 'ByteWise',
      category: 'Lifestyle',
      date: '2024-07-23T09:35:14Z',
      amount: -49.99,
      recurring: true,
      id: '4201',
    },
    {
      avatar: './assets/images/avatars/nimbus-data-storage.jpg',
      name: 'Nimbus Data Storage',
      category: 'Bills',
      date: '2024-07-21T10:05:42Z',
      amount: -9.99,
      recurring: true,
      id: 'f33f',
    },
    {
      avatar: './assets/images/avatars/emma-richardson.jpg',
      name: 'Emma Richardson',
      category: 'General',
      date: '2024-07-20T17:30:55Z',
      amount: -25,
      recurring: false,
      id: 'c927',
    },
    {
      avatar: './assets/images/avatars/daniel-carter.jpg',
      name: 'Daniel Carter',
      category: 'General',
      date: '2024-07-19T12:45:09Z',
      amount: 50,
      recurring: false,
      id: '5ec2',
    },
    {
      avatar: './assets/images/avatars/sun-park.jpg',
      name: 'Sun Park',
      category: 'General',
      date: '2024-07-18T19:20:23Z',
      amount: -38.5,
      recurring: false,
      id: '1c62',
    },
    {
      avatar: './assets/images/avatars/harper-edwards.jpg',
      name: 'Harper Edwards',
      category: 'Shopping',
      date: '2024-07-17T14:55:37Z',
      amount: -29.99,
      recurring: false,
      id: '41bc',
    },
    {
      avatar: './assets/images/avatars/liam-hughes.jpg',
      name: 'Liam Hughes',
      category: 'Groceries',
      date: '2024-07-16T10:10:51Z',
      amount: -52.75,
      recurring: false,
      id: 'e4e7',
    },
    {
      avatar: './assets/images/avatars/lily-ramirez.jpg',
      name: 'Lily Ramirez',
      category: 'General',
      date: '2024-07-15T16:35:04Z',
      amount: 75,
      recurring: false,
      id: '7bf9',
    },
    {
      avatar: './assets/images/avatars/ethan-clark.jpg',
      name: 'Ethan Clark',
      category: 'Dining Out',
      date: '2024-07-14T20:50:18Z',
      amount: -41.25,
      recurring: false,
      id: 'dbac',
    },
    {
      avatar: './assets/images/avatars/rina-sato.jpg',
      name: 'Rina Sato',
      category: 'Entertainment',
      date: '2024-07-13T09:15:32Z',
      amount: -10,
      recurring: false,
      id: '0aaf',
    },
    {
      avatar: './assets/images/avatars/james-thompson.jpg',
      name: 'James Thompson',
      category: 'Bills',
      date: '2024-07-12T13:40:46Z',
      amount: -95.5,
      recurring: false,
      id: 'c79a',
    },
    {
      avatar: './assets/images/avatars/ella-phillips.jpg',
      name: 'Ella Phillips',
      category: 'Dining Out',
      date: '2024-07-11T18:05:59Z',
      amount: -33.75,
      recurring: false,
      id: '4f18',
    },
    {
      avatar: './assets/images/avatars/yuna-kim.jpg',
      name: 'Yuna Kim',
      category: 'Dining Out',
      date: '2024-07-10T12:30:13Z',
      amount: -27.5,
      recurring: false,
      id: 'f780',
    },
    {
      avatar: './assets/images/avatars/sofia-peterson.jpg',
      name: 'Sofia Peterson',
      category: 'Transportation',
      date: '2024-07-09T08:55:27Z',
      amount: -12.5,
      recurring: false,
      id: '7934',
    },
    {
      avatar: './assets/images/avatars/mason-martinez.jpg',
      name: 'Mason Martinez',
      category: 'Lifestyle',
      date: '2024-07-08T15:20:41Z',
      amount: -65,
      recurring: false,
      id: '854c',
    },
    {
      avatar: './assets/images/avatars/sebastian-cook.jpg',
      name: 'Sebastian Cook',
      category: 'Transportation',
      date: '2024-07-07T11:45:55Z',
      amount: -20,
      recurring: false,
      id: '6c06',
    },
    {
      avatar: './assets/images/avatars/william-harris.jpg',
      name: 'William Harris',
      category: 'General',
      date: '2024-07-06T17:10:09Z',
      amount: 20,
      recurring: false,
      id: 'e442',
    },
    {
      avatar: './assets/images/avatars/elevate-education.jpg',
      name: 'Elevate Education',
      category: 'Education',
      date: '2024-07-05T11:15:22Z',
      amount: -50,
      recurring: true,
      id: 'acfe',
    },
    {
      avatar: './assets/images/avatars/serenity-spa-and-wellness.jpg',
      name: 'Serenity Spa & Wellness',
      category: 'Personal Care',
      date: '2024-07-03T14:00:37Z',
      amount: -30,
      recurring: true,
      id: '4b09',
    },
    {
      avatar: './assets/images/avatars/spark-electric-solutions.jpg',
      name: 'Spark Electric Solutions',
      category: 'Bills',
      date: '2024-07-02T09:25:51Z',
      amount: -100,
      recurring: true,
      id: '6eb6',
    },
    {
      avatar: './assets/images/avatars/swift-ride-share.jpg',
      name: 'Swift Ride Share',
      category: 'Transportation',
      date: '2024-07-02T19:50:05Z',
      amount: -16.5,
      recurring: false,
      id: '6725',
    },
  ],
  budgets: [
    {
      category: 'Entertainment',
      maximum: 50,
      theme: '#277C78',
      id: '0b26',
    },
    {
      category: 'Bills',
      maximum: 750,
      theme: '#82C9D7',
      id: '3097',
    },
    {
      category: 'Dining Out',
      maximum: 75,
      theme: '#F2CDAC',
      id: '242f',
    },
    {
      id: '4d08983f-7b8c-4bf7-85d4-c47d575a634f',
      category: 'Education',
      maximum: 200,
      theme: '#be6c49',
    },
  ],
  pots: [
    {
      name: 'Savings',
      target: 2000,
      total: 159,
      theme: '#277C78',
      id: 'd0e1',
    },
    {
      name: 'Concert Ticket',
      target: 150,
      total: 110,
      theme: '#626070',
      id: 'a962',
    },
    {
      name: 'Gift',
      target: 150,
      total: 110,
      theme: '#82C9D7',
      id: '3e41',
    },
    {
      name: 'New Laptop',
      target: 1000,
      total: 10,
      theme: '#F2CDAC',
      id: '8374',
    },
  ],
};
